# Generated by Django 5.1.6 on 2025-04-07 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad_aprendizaje', '0001_initial'),
        ('competencias_genericas', '0001_initial'),
        ('estrategia_ensenanza', '0001_initial'),
        ('indicador_alcance', '0001_initial'),
        ('lista_cotejo', '0001_initial'),
        ('nivel_desempenio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('horas', models.IntegerField()),
                ('actividad_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='actividad_aprendizaje.actividadaprendizaje')),
                ('competencia_generica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='competencias_genericas.competenciagenerica')),
                ('estrategia_ensenanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='estrategia_ensenanza.estrategiaensenanza')),
                ('indicador_alcance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='indicador_alcance.indicadoralcance')),
                ('lista_cotejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='lista_cotejo.listacotejo')),
                ('nivel_desempeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='nivel_desempenio.niveldesempenio')),
            ],
        ),
    ]
