# Generated by Django 5.1.6 on 2025-04-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliografia', '0001_initial'),
        ('competencia', '0001_initial'),
        ('criterio_desempeno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('creditos_requeridos', models.IntegerField(default=0)),
                ('semestre', models.CharField(max_length=50)),
                ('tipo_curso', models.BooleanField(help_text='True = Obligatoria, False = Optativa')),
                ('creditos_teoria', models.IntegerField()),
                ('creditos_practica', models.IntegerField()),
                ('horas_ciencias_basicas', models.IntegerField()),
                ('horas_ciencias_ingenieria', models.IntegerField()),
                ('horas_ingenieria_aplicada', models.IntegerField()),
                ('horas_disenio_ingenieril', models.IntegerField()),
                ('horas_ciencias_sociales', models.IntegerField()),
                ('horas_ciencias_economicas', models.IntegerField()),
                ('horas_otros_cursos', models.IntegerField()),
                ('objetivo_general', models.TextField()),
                ('indicador_descripcion', models.TextField()),
                ('bibliografia', models.ManyToManyField(related_name='materias', to='bibliografia.bibliografia')),
                ('competencias', models.ManyToManyField(related_name='materias', to='competencia.competencia')),
                ('criterio_desempeno', models.ManyToManyField(related_name='materias', to='criterio_desempeno.criteriodesempeno')),
                ('materias_requeridas', models.ManyToManyField(blank=True, related_name='materias_dependientes', to='materias.materia')),
            ],
        ),
    ]
