# Generated by Django 5.1.6 on 2025-04-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('L', 'Licenciatura'), ('E', 'Especialidad'), ('M', 'Maestría'), ('D', 'Doctorado')], max_length=1)),
                ('nombre', models.CharField(max_length=255)),
                ('anio_obtencion', models.IntegerField()),
                ('cedula_profesional', models.CharField(max_length=100, unique=True)),
                ('institucion_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formaciones_academicas', to='institucion.institucionpais')),
            ],
        ),
    ]
