# Generated by Django 5.1.6 on 2025-05-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_academica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacionacademica',
            name='anio_obtencion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='cedula_profesional',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='nivel',
            field=models.CharField(blank=True, choices=[('L', 'Licenciatura'), ('E', 'Especialidad'), ('M', 'Maestría'), ('D', 'Doctorado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
