# Generated by Django 5.1.6 on 2025-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0001_initial'),
        ('temas', '0002_temas_sub_temas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='temas',
        ),
        migrations.AddField(
            model_name='competencia',
            name='temas',
            field=models.ManyToManyField(related_name='competencias', to='temas.temas'),
        ),
    ]
