# Generated by Django 5.1.6 on 2025-04-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0002_remove_competencia_temas_competencia_temas'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
