# Generated by Django 5.1.6 on 2025-04-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='clave',
        ),
    ]
