# Generated by Django 5.1.6 on 2025-04-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0002_remove_periodo_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='clave',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
