# Generated by Django 5.1.6 on 2025-03-19 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criterio_desempeno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('criterios_desempeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_egreso', to='criterio_desempeno.criteriodesempeno')),
            ],
        ),
    ]
