# Generated by Django 5.1.6 on 2025-05-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atributo_egreso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributoegreso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
