# Generated by Django 5.1.6 on 2025-04-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isssn', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('ieee', models.TextField()),
                ('anio', models.IntegerField()),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
