# Generated by Django 5.1.6 on 2025-04-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliografia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliografia',
            name='ficha_bibtex',
        ),
        migrations.AddField(
            model_name='bibliografia',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bibliografia',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
