# Generated by Django 5.1.6 on 2025-03-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AreaAdscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('siglas', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CapacitacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_capacitacion', models.CharField(max_length=255)),
                ('anio_obtencion', models.PositiveIntegerField()),
                ('horas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaDisenoIngenieril',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organismo', models.CharField(max_length=255)),
                ('periodo', models.IntegerField()),
                ('nivel_experiencia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfesionalNoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_puesto', models.CharField(max_length=255)),
                ('organizacion_empresa', models.CharField(max_length=255)),
                ('d_mes_anio', models.DateField()),
                ('a_mes_anio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('L', 'Licenciatura'), ('E', 'Especialidad'), ('M', 'Maestría'), ('D', 'Doctorado')], max_length=1)),
                ('nombre', models.CharField(max_length=255)),
                ('anio_obtencion', models.IntegerField()),
                ('cedula_profesional', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GestionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_puesto', models.CharField(max_length=255)),
                ('d_mes_anio', models.DateField()),
                ('a_mes_anio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LogrosProfesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organismo', models.CharField(max_length=255)),
                ('periodo', models.IntegerField()),
                ('nivel_p', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosAcademicosRelevantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_producto_academico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActualizacionDisciplinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actualizacion', models.CharField(max_length=255)),
                ('anio_obtencion', models.PositiveIntegerField()),
                ('horas', models.PositiveIntegerField()),
                ('institucion_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones_disciplinarias', to='institucion.institucionpais')),
            ],
        ),
    ]
