# Generated by Django 5.1.6 on 2025-02-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_customuser_managers_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_docente',
            field=models.CharField(blank=True, choices=[('basificado', 'Basificado'), ('asignatura', 'basificado')], max_length=20, null=True),
        ),
    ]
