# Generated by Django 5.1.6 on 2025-03-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_delete_formacionacademica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapacitacionDocente',
        ),
    ]
