# Generated by Django 5.1.6 on 2025-02-27 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_customuser_tipo_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('L', 'Licenciatura'), ('E', 'Especialidad'), ('M', 'Maestria'), ('D', 'Doctorado')], max_length=1)),
                ('nombre', models.CharField(max_length=255)),
                ('institucion_pais', models.CharField(max_length=255)),
                ('año_obtencion', models.IntegerField()),
                ('cedula_profesional', models.CharField(max_length=100, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacion_academica', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
