# Generated by Django 5.1.6 on 2025-02-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_formacionacademica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formacionacademica',
            old_name='año_obtencion',
            new_name='anio_obtencion',
        ),
        migrations.AlterField(
            model_name='formacionacademica',
            name='nivel',
            field=models.CharField(choices=[('L', 'Licenciatura'), ('E', 'Especialidad'), ('M', 'Maestría'), ('D', 'Doctorado')], max_length=1),
        ),
    ]
