# Generated by Django 5.1.6 on 2025-02-27 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_año_obtencion_formacionacademica_anio_obtencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombreProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nombre_profesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
