# Generated by Django 5.1.6 on 2025-02-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_customuser_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
