# Generated by Django 5.1.6 on 2025-02-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_customuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
    ]
