# Generated by Django 5.1.6 on 2025-02-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_institucionpais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacionacademica',
            name='institucion_pais',
        ),
    ]
