# Generated by Django 5.1.6 on 2025-03-02 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_productosacademicosrelevantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaProfesionalNoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_puesto', models.CharField(max_length=255)),
                ('organizacion_empresa', models.CharField(max_length=255)),
                ('d_mes_año', models.DateField()),
                ('a_mes_año', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
