# Generated by Django 5.1.6 on 2025-03-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_experienciadiseñoingenieril'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciadiseñoingenieril',
            name='periodo',
            field=models.IntegerField(),
        ),
    ]
