# Generated by Django 5.1.6 on 2025-03-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_aportacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperienciaDiseñoIngenieril',
            new_name='ExperienciaDisenoIngenieril',
        ),
        migrations.RenameField(
            model_name='actualizaciondisciplinaria',
            old_name='año_obtencion',
            new_name='anio_obtencion',
        ),
        migrations.RenameField(
            model_name='capacitaciondocente',
            old_name='año_obtencion',
            new_name='anio_obtencion',
        ),
        migrations.RenameField(
            model_name='experienciaprofesionalnoacademica',
            old_name='a_mes_año',
            new_name='a_mes_anio',
        ),
        migrations.RenameField(
            model_name='experienciaprofesionalnoacademica',
            old_name='d_mes_año',
            new_name='d_mes_anio',
        ),
        migrations.RenameField(
            model_name='gestionacademica',
            old_name='a_mes_año',
            new_name='a_mes_anio',
        ),
        migrations.RenameField(
            model_name='gestionacademica',
            old_name='d_mes_año',
            new_name='d_mes_anio',
        ),
    ]
