# Generated by Django 5.1.6 on 2025-03-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_rename_experienciadiseñoingenieril_experienciadisenoingenieril_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
    ]
