# Generated by Django 5.1.6 on 2025-03-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_customuser_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucionpais',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
    ]
