# Generated by Django 5.1.6 on 2025-03-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_institucionpais_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAdscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('siglas', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
    ]
