# Generated by Django 5.1.6 on 2025-03-07 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_areaadscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='area_adscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='registration.areaadscripcion'),
        ),
    ]
