# Generated by Django 5.1.6 on 2025-05-07 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_alumno_is_active_alter_alumno_apellido_materno_and_more'),
        ('carrera', '0002_carrera_is_active_carrera_mision_and_more'),
        ('clase', '0001_initial'),
        ('materias', '0001_initial'),
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='clases', to='alumno.alumno'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='carrera.carrera'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='grupo',
            field=models.CharField(blank=True, choices=[('01', 'Grupo 01'), ('02', 'Grupo 02'), ('03', 'Grupo 03')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='materias.materia'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='periodo.periodo'),
        ),
    ]
