# Generated by Django 5.1.6 on 2025-05-14 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_alter_clase_alumnos_alter_clase_carrera_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_docente', to=settings.AUTH_USER_MODEL),
        ),
    ]
