# Generated by Django 5.1.6 on 2025-04-09 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoEducacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_educacionales', to='carrera.carrera')),
            ],
        ),
    ]
