# Generated by Django 5.1.6 on 2025-04-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criterio_desempeno', '0001_initial'),
        ('estrategia_ensenanza', '0001_initial'),
        ('estrategia_evaluacion', '0001_initial'),
        ('practica', '0001_initial'),
        ('sub_temas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('objetivo', models.TextField()),
                ('criterio_desempeno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='criterio_desempeno.criteriodesempeno')),
                ('estrategia_ensenanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='estrategia_ensenanza.estrategiaensenanza')),
                ('estrategia_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='estrategia_evaluacion.estrategiaevaluacion')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='practica.practica')),
                ('sub_temas', models.ManyToManyField(blank=True, related_name='temas', to='sub_temas.subtema')),
            ],
        ),
    ]
