# Generated by Django 5.1.6 on 2025-03-19 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adscripcion', '0001_initial'),
        ('atributo_egreso', '0001_initial'),
        ('objetivos_especificos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('adscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adscripcion', to='adscripcion.areaadscripcion')),
                ('atributos_egreso', models.ManyToManyField(blank=True, related_name='carreras', to='atributo_egreso.atributoegreso')),
                ('objetivos_especificos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_espesificos', to='objetivos_especificos.objetivosespecificos')),
            ],
        ),
    ]
