# Generated by Django 5.1.6 on 2025-04-09 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adscripcion', '0001_initial'),
        ('atributo_egreso', '0001_initial'),
        ('objetivos_especificos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('adscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='adscripcion.areaadscripcion')),
                ('atributos_egreso', models.ManyToManyField(related_name='carreras', to='atributo_egreso.atributoegreso')),
                ('objetivo_especifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='objetivos_especificos.objetivosespecificos')),
            ],
        ),
    ]
