# Generated by Django 5.1.6 on 2025-05-07 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adscripcion', '0001_initial'),
        ('atributo_egreso', '0001_initial'),
        ('carrera', '0001_initial'),
        ('objetivos_especificos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carrera',
            name='mision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrera',
            name='objetivo_carrera',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrera',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='adscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='adscripcion.areaadscripcion'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='atributos_egreso',
            field=models.ManyToManyField(blank=True, related_name='carreras', to='atributo_egreso.atributoegreso'),
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='objetivo_especifico',
        ),
        migrations.AddField(
            model_name='carrera',
            name='objetivo_especifico',
            field=models.ManyToManyField(blank=True, related_name='carreras', to='objetivos_especificos.objetivosespecificos'),
        ),
    ]
