# Generated by Django 5.1.6 on 2025-03-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criterio_desempeno', '0001_initial'),
        ('objetivos_especificos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('creditos_requeridos', models.IntegerField(blank=True, default=0, null=True)),
                ('semestre', models.CharField(max_length=50)),
                ('tipo_curso', models.CharField(choices=[('obligatorio', 'Obligatorio'), ('optativo', 'Optativo')], max_length=20)),
                ('creditos_teoria', models.IntegerField()),
                ('creditos_practica', models.IntegerField()),
                ('horas_ciencias_basicas', models.IntegerField()),
                ('horas_ciencias_ingenieria', models.IntegerField()),
                ('horas_ingenieria_aplicada', models.IntegerField()),
                ('horas_diseno_ingeniril', models.IntegerField()),
                ('horas_ciencias_sociales', models.IntegerField()),
                ('horas_ciencias_economicas', models.IntegerField()),
                ('horas_otros_cursos', models.IntegerField()),
                ('objetivo_general', models.TextField()),
                ('indicador_descripcion', models.TextField()),
                ('idcriterio_desempeno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='criterio_desempeno.criteriodesempeno')),
                ('materias_requeridas', models.ManyToManyField(blank=True, related_name='materias_dependientes', to='materia.materia')),
                ('objetivos_especificos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to='objetivos_especificos.objetivosespecificos')),
            ],
        ),
    ]
