# Generated by Django 5.1.6 on 2025-04-25 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('alumno', '0001_initial'),
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_directas', to='actividad.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='alumno.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='clase.clase')),
            ],
        ),
    ]
