# Generated by Django 5.1.6 on 2025-04-09 05:14

import actividad.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.FileField(upload_to='actividades/descripcion/')),
                ('formato', models.FileField(upload_to=actividad.models.formato_path)),
                ('alumno_alto_calificacion', models.FloatField()),
                ('alumno_alto_evidencia', models.FileField(upload_to=actividad.models.evidencia_path)),
                ('alumno_promedio_calificacion', models.FloatField()),
                ('alumno_promedio_evidencia', models.FileField(upload_to=actividad.models.evidencia_path)),
                ('alumno_bajo_calificacion', models.FloatField()),
                ('alumno_bajo_evidencia', models.FileField(upload_to=actividad.models.evidencia_path)),
                ('alumno_alto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_alto', to='alumno.alumno')),
                ('alumno_bajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_bajo', to='alumno.alumno')),
                ('alumno_promedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_promedio', to='alumno.alumno')),
            ],
        ),
    ]
