# Generated by Django 5.1.6 on 2025-04-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
        ('calificaciones', '0002_alter_calificacion_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='calificaciones',
            field=models.ManyToManyField(blank=True, related_name='actividades', to='calificaciones.calificacion'),
        ),
    ]
