# Generated by Django 5.1.6 on 2025-04-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='calificaciones',
            field=models.ManyToManyField(blank=True, related_name='actividades', to='calificaciones.calificacion'),
        ),
    ]
