# Generated by Django 5.1.6 on 2025-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0003_alter_actividad_alumno_alto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
