# Generated by Django 5.1.6 on 2025-05-21 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0004_actividad_titulo'),
        ('clase', '0003_clase_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='clase.clase'),
        ),
    ]
